version: '3'
services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/moemoe89/go-graphql-gendhis
    container_name: go_graphql_gendhis
    restart: always
    ports:
      - "8791:8791"
    tty: true
    depends_on:
      - postgres
    networks:
      - fullstack
  postgres:
    image: postgres:12.1
    container_name: postgres
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'simple_api'
    ports:
      - 5433:5432
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge